# fly.toml app configuration file generated for metro-packaging-depot-if4yw on 2026-09-04T14:41:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metro-packaging-depot-if4yw'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
